version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout 
      - run: go mod vendor 
      - run: go test -v -race $(go list ./... | grep -v /vendor/) -coverprofile=coverage.txt
      - run: bash <(curl -s https://codecov.io/bash) -t 00b410bb-3c92-4ef7-82d9-364a6a160dd6